version: '3'
services:
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
      - "50051:50051"
    depends_on:
      - users

  users:
    container_name: users
    build:
      context: ./users
      dockerfile: Dockerfile
    ports:
      - "3000:3000"