# Sử dụng Node.js làm base image
FROM node:18

# Đặt thư mục làm việc trong container
WORKDIR /app

# Sao chép package.json và cài đặt dependencies
COPY package*.json ./
RUN npm install

# Sao chép toàn bộ mã nguồn vào container
COPY . .

# Biên dịch TypeScript
RUN npm run build

# Mở cổng HTTP 3000
EXPOSE 3000

# Chạy ứng dụng
CMD ["npm", "run", "start:prod"]